Repository yiisoft/input-http, pull requests merged in 2024-03, with the labels that each got.

#26 Move request provider code to a separate package + Raise PHP to 8.1
  .github/workflows/build.yml
  .github/workflows/composer-require-checker.yml
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  .gitignore
  composer.json
  config/di-web.php
  phpunit.xml.dist
  src/Attribute/Data/FromBodyResolver.php
  src/Attribute/Data/FromQueryResolver.php
  src/Attribute/Parameter/BodyResolver.php
  src/Attribute/Parameter/QueryResolver.php
  src/Attribute/Parameter/RequestResolver.php
  src/Attribute/Parameter/UploadedFilesResolver.php
  src/Request/Catcher/RequestCatcherMiddleware.php
  src/Request/Catcher/RequestCatcherParametersResolver.php
  src/Request/RequestNotSetException.php
  src/Request/RequestProvider.php
  src/Request/RequestProviderInterface.php
  tests/Attribute/Data/FromBodyTest.php
  tests/Attribute/Data/FromQueryTest.php
  tests/Attribute/Parameter/BodyTest.php
  tests/Attribute/Parameter/QueryTest.php
  tests/Attribute/Parameter/RequestTest.php
  tests/Attribute/Parameter/UploadedFilesTest.php
  tests/ConfigTest.php
  tests/HydratorAttributeParametersResolverTest.php
  tests/Request/Catcher/RequestCatcherMiddlewareTest.php
  tests/Request/Catcher/RequestCatcherParametersResolverTest.php
  tests/Request/RequestNotSetExceptionTest.php
  tests/Request/RequestProviderTest.php
  tests/RequestInputParametersResolverTest.php
  tests/Support/TestHelper.php
  tests/TestEnvironments/Php81/RequestInputParametersResolverTest.php
Labels: status:code review, type:task

#30 Actualize request provider docs
  README.md
  docs/guide/en/storing-request.md
Labels: type:docs

#31 Fix PHP version in readme
  README.md
Labels: type:docs

#32 Remove old link
  docs/guide/en/README.md
Labels: type:docs

#34 Raise `yiisoft/hydrator-validator` to `^2.0`
  composer.json
  src/RequestInputParametersResolver.php
  tests/RequestInputParametersResolverTest.php
Labels: status:code review

#36 Enable BC workflow
  .github/workflows/bc.yml
Labels: type:task
